# Generated by Django 3.0.4 on 2020-03-15 15:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0003_article_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='author_image',
            field=models.FileField(default=django.utils.timezone.now, upload_to=''),
            preserve_default=False,
        ),
    ]
